name: interview
description: interview
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  get: ^3.24.0
  json_annotation: ^3.1.0
  freezed_annotation: ^0.12.0
  fl_chart: ^0.12.2
  intl: ^0.16.1


dev_dependencies:
  build_runner: ^1.10.13
  freezed: ^0.12.2
  json_serializable: ^3.5.0

flutter_icons:
  android: ic_launcher
  ios: true
  image_path_ios: assets/images/logo.jpg # can't be adaptive
  image_path_android: assets/images/logo.jpg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/logo.png # 300

flutter_native_splash:
  image: assets/icons/logo.png # must be png
  color: "#FFFFFF"
  fill: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/anims/
